version: '3.4'

services:
  stamacasa.api:
    image: ${DOCKER_REGISTRY-}stamacasa-api
    build:
      context: .
      dockerfile: StamAcasa.Api/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 5008:80
    depends_on:
      - postgres
      - identityserver
    # volumes: 
      #- ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
      #- ${HOME}/.aspnet/https:/root/.aspnet/https/

  rabbitmq:
    image: local_rabbit
    restart: always
    container_name: rabbitmq
    build:
      context: rabbitconfig/
      dockerfile: Dockerfile
    ports:
       # The standard AMQP protocol port
      - 5672:5672
        # HTTP management UI
      - 15672:15672

  identityserver:
    image: ${DOCKER_REGISTRY-}stamacasa-identityserver
    environment:
      - ASPNETCORE_URLS=http://+:80
    build:
        context: .
        dockerfile: StamAcasa.IdentityServer/Dockerfile
    ports:
      - 5001:80
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=docker
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - /postgres_data:/var/lib/postgresql/data

  frontend:
    image:  ${DOCKER_REGISTRY-}stamacasa
    container_name: stamacasa
    build:
        context: ../../frontend
        dockerfile: Dockerfile
    environment:
      REACT_APP_IDP_URL: 'http://localhost:5001'
      REACT_APP_URL: 'http://localhost:5002'
      REACT_APP_API_URL: 'http://localhost:5008'
      CLIENT_ID: 'jsdocker'
    ports:
     - 5002:5002
    depends_on:
      - stamacasa.api

  stamacasa.email:
    image: ${DOCKER_REGISTRY-}stamacasa-email
    build:
        context: .
        dockerfile: StamAcasa.EmailService/Dockerfile
    depends_on:
      - rabbitmq